/**
 * @file
 *
 * The policy gsec_x509_path applies on top of RFC 5280's algorithm, and the
 * rules it already applied that nothing tested.
 *
 * Every one of these was a mutation that survived `make test` on 2026-09-28:
 * pathLenConstraint, the keyCertSign requirement, and the signature-algorithm
 * to issuer-key match. The rest - weak digests, small keys, an expired
 * anchor, extendedKeyUsage - are rules added because the audit found the
 * chain validating without them.
 *
 * The instant each test validates at is read from the certificates rather
 * than hardcoded, so a fixture regenerated by tools/make-fixtures.sh does not
 * expire and does not have to be regenerated in step with the tests.
 *
 * Copyright 2026 by Corey Pennycuff
 */

#include "test_helpers.h"

#include <cstdint>
#include <fstream>
#include <vector>

namespace {

std::vector<unsigned char> load(const char * name) {
  std::ifstream in(gsectest::data_dir() + "/certs/" + name, std::ios::binary);
  EXPECT_TRUE(in.good()) << name;
  return std::vector<unsigned char>(std::istreambuf_iterator<char>(in),
      std::istreambuf_iterator<char>());
}

/* An instant inside both certificates' validity periods. */
int64_t both_valid(const std::vector<unsigned char> & a,
    const std::vector<unsigned char> & b) {
  GSEC_X509 pa;
  GSEC_X509 pb;
  EXPECT_EQ(gsec_x509_parse(a.data(), a.size(), &pa), GSEC_OK);
  EXPECT_EQ(gsec_x509_parse(b.data(), b.size(), &pb), GSEC_OK);
  int64_t from = pa.not_before > pb.not_before ? pa.not_before : pb.not_before;
  int64_t to = pa.not_after < pb.not_after ? pa.not_after : pb.not_after;
  return from + (to - from) / 2;
}

GSEC_Result path(const std::vector<unsigned char> & leaf,
    const std::vector<unsigned char> & anchor, int64_t when,
    unsigned purpose = 0) {
  return gsec_x509_path(leaf.data(), leaf.size(), nullptr, nullptr, 0,
      anchor.data(), anchor.size(), when, purpose);
}

GSEC_Result path_mid(const std::vector<unsigned char> & leaf,
    const std::vector<unsigned char> & mid,
    const std::vector<unsigned char> & anchor, int64_t when) {
  const void * mids[1] = {mid.data()};
  size_t lens[1] = {mid.size()};
  return gsec_x509_path(leaf.data(), leaf.size(), mids, lens, 1, anchor.data(),
      anchor.size(), when, 0);
}

} /* namespace */

/* --- Weak digests ------------------------------------------------------- */

TEST(X509Policy, Sha1ChainIsRefusedButStillVerifies) {
  auto ca = load("sha1-ca.der");
  auto leaf = load("sha1-leaf.der");
  GSEC_X509 pl;
  GSEC_X509 pc;
  ASSERT_EQ(gsec_x509_parse(leaf.data(), leaf.size(), &pl), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(ca.data(), ca.size(), &pc), GSEC_OK);
  EXPECT_EQ(pl.sig_hash, GSEC_RSA_SHA1);
  /* The signature is real: this is how a caller identifies an old
   * certificate. What it must not do is pass for a valid chain. */
  EXPECT_EQ(gsec_x509_signed_by(&pl, &pc), GSEC_OK);
  EXPECT_EQ(path(leaf, ca, both_valid(leaf, ca)), GSEC_ERR_UNSUPPORTED);
}

TEST(X509Policy, Md5ChainIsRefusedButStillVerifies) {
  auto ca = load("md5-ca.der");
  auto leaf = load("md5-leaf.der");
  GSEC_X509 pl;
  GSEC_X509 pc;
  ASSERT_EQ(gsec_x509_parse(leaf.data(), leaf.size(), &pl), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(ca.data(), ca.size(), &pc), GSEC_OK);
  EXPECT_EQ(pl.sig_hash, GSEC_RSA_MD5);
  EXPECT_EQ(gsec_x509_signed_by(&pl, &pc), GSEC_OK);
  EXPECT_EQ(path(leaf, ca, both_valid(leaf, ca)), GSEC_ERR_UNSUPPORTED);
}

/* --- Key size ----------------------------------------------------------- */

TEST(X509Policy, SmallRsaKeyIsRefused) {
  auto ca = load("weakkey-ca.der");
  auto leaf = load("weakkey-leaf.der");
  GSEC_X509 pl;
  ASSERT_EQ(gsec_x509_parse(leaf.data(), leaf.size(), &pl), GSEC_OK);
  EXPECT_EQ(pl.key, GSEC_X509_RSA);
  EXPECT_LT(pl.n_len * 8u, GSEC_X509_RSA_MIN_BITS);
  EXPECT_EQ(path(leaf, ca, both_valid(leaf, ca)), GSEC_ERR_UNSUPPORTED);
}

TEST(X509Policy, TwoThousandFortyEightBitKeyIsAccepted) {
  auto ca = load("sha1-ca.der");
  GSEC_X509 pc;
  ASSERT_EQ(gsec_x509_parse(ca.data(), ca.size(), &pc), GSEC_OK);
  /* The control for the test above: the same generator, the same shape, a
   * key that clears the floor. Only the digest makes that chain fail. */
  EXPECT_GE(pc.n_len * 8u, GSEC_X509_RSA_MIN_BITS);
}

/* --- The anchor's own validity ------------------------------------------ */

TEST(X509Policy, ExpiredAnchorIsRefused) {
  auto ca = load("shortca-ca.der");
  auto leaf = load("shortca-leaf.der");
  GSEC_X509 pc;
  GSEC_X509 pl;
  ASSERT_EQ(gsec_x509_parse(ca.data(), ca.size(), &pc), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(leaf.data(), leaf.size(), &pl), GSEC_OK);
  /* The anchor is good for two days and the leaf for ten years, so there is
   * an instant where only the anchor has expired. RFC 5280 section 6.1 does
   * not examine the anchor's dates; this library does. */
  int64_t after_ca = pc.not_after + 1;
  ASSERT_LT(after_ca, pl.not_after);
  ASSERT_GT(after_ca, pl.not_before);
  EXPECT_EQ(path(leaf, ca, after_ca), GSEC_ERR_MISMATCH);
  EXPECT_EQ(path(leaf, ca, pc.not_after), GSEC_OK);
}

/* --- extendedKeyUsage --------------------------------------------------- */

TEST(X509Policy, EkuIsParsedAndNotDiscarded) {
  auto server = load("eku-server.der");
  auto code = load("eku-code.der");
  auto any = load("eku-any.der");
  auto both = load("eku-both.der");
  auto unknown = load("eku-unknown.der");
  GSEC_X509 p;

  ASSERT_EQ(gsec_x509_parse(server.data(), server.size(), &p), GSEC_OK);
  EXPECT_EQ(p.eku_set, 1);
  EXPECT_EQ(p.eku, GSEC_X509_EKU_SERVER_AUTH);
  EXPECT_EQ(p.eku_critical, 0);
  EXPECT_EQ(p.eku_unknown, 0);

  ASSERT_EQ(gsec_x509_parse(code.data(), code.size(), &p), GSEC_OK);
  EXPECT_EQ(p.eku, GSEC_X509_EKU_CODE_SIGNING);
  EXPECT_EQ(p.eku_critical, 1);

  ASSERT_EQ(gsec_x509_parse(any.data(), any.size(), &p), GSEC_OK);
  EXPECT_EQ(p.eku, GSEC_X509_EKU_ANY);

  ASSERT_EQ(gsec_x509_parse(both.data(), both.size(), &p), GSEC_OK);
  EXPECT_EQ(p.eku,
      GSEC_X509_EKU_SERVER_AUTH | GSEC_X509_EKU_CLIENT_AUTH);

  ASSERT_EQ(gsec_x509_parse(unknown.data(), unknown.size(), &p), GSEC_OK);
  EXPECT_EQ(p.eku_set, 1);
  EXPECT_EQ(p.eku, 0u);
  EXPECT_EQ(p.eku_unknown, 1);
}

TEST(X509Policy, PurposeIsEnforcedWhenAsked) {
  auto server = load("eku-server.der");
  auto code = load("eku-code.der");
  auto any = load("eku-any.der");
  auto unknown = load("eku-unknown.der");
  auto plain = load("p256-leaf.der");
  GSEC_X509 ps;
  GSEC_X509 pc;
  GSEC_X509 pa;
  GSEC_X509 pu;
  GSEC_X509 pp;
  ASSERT_EQ(gsec_x509_parse(server.data(), server.size(), &ps), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(code.data(), code.size(), &pc), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(any.data(), any.size(), &pa), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(unknown.data(), unknown.size(), &pu), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(plain.data(), plain.size(), &pp), GSEC_OK);

  EXPECT_EQ(gsec_x509_purpose(&ps, GSEC_X509_EKU_SERVER_AUTH), GSEC_OK);
  EXPECT_EQ(gsec_x509_purpose(&ps, GSEC_X509_EKU_CODE_SIGNING),
      GSEC_ERR_MISMATCH);
  /* The case the audit named: a certificate issued for code signing, marked
   * critical, must not pass as a TLS server certificate. */
  EXPECT_EQ(gsec_x509_purpose(&pc, GSEC_X509_EKU_SERVER_AUTH),
      GSEC_ERR_MISMATCH);
  EXPECT_EQ(gsec_x509_purpose(&pa, GSEC_X509_EKU_SERVER_AUTH), GSEC_OK);
  /* Purposes this parser has no bit for are not a licence. */
  EXPECT_EQ(gsec_x509_purpose(&pu, GSEC_X509_EKU_SERVER_AUTH),
      GSEC_ERR_MISMATCH);
  /* No extension at all permits everything, which is RFC 5280. */
  EXPECT_EQ(gsec_x509_purpose(&pp, GSEC_X509_EKU_SERVER_AUTH), GSEC_OK);
  EXPECT_EQ(gsec_x509_purpose(nullptr, GSEC_X509_EKU_SERVER_AUTH),
      GSEC_ERR_INVALID);
  EXPECT_EQ(gsec_x509_purpose(&ps, 0), GSEC_ERR_INVALID);
}

TEST(X509Policy, PathChecksThePurposeItIsGiven) {
  auto ca = load("sha1-ca.der");
  auto code = load("eku-code.der");
  /* eku-code.der is self-signed, so it is its own anchor: this isolates the
   * purpose check from every other rule. */
  int64_t when = both_valid(code, code);
  EXPECT_EQ(path(code, code, when, 0), GSEC_OK);
  EXPECT_EQ(path(code, code, when, GSEC_X509_EKU_CODE_SIGNING), GSEC_OK);
  EXPECT_EQ(path(code, code, when, GSEC_X509_EKU_SERVER_AUTH),
      GSEC_ERR_MISMATCH);
  (void)ca;
}

/* --- pathLenConstraint -------------------------------------------------- */

TEST(X509Policy, PathLenZeroRefusesAnIntermediate) {
  auto ca = load("plen-ca.der");
  auto mid = load("plen-mid.der");
  auto leaf = load("plen-leaf.der");
  auto direct = load("plen-direct.der");
  GSEC_X509 pc;
  ASSERT_EQ(gsec_x509_parse(ca.data(), ca.size(), &pc), GSEC_OK);
  EXPECT_EQ(pc.path_len_set, 1);
  EXPECT_EQ(pc.path_len, 0u);
  int64_t when = both_valid(leaf, ca);
  /* pathlen:0 permits end-entity certificates and no further CA. */
  EXPECT_EQ(path(direct, ca, when), GSEC_OK);
  EXPECT_EQ(path_mid(leaf, mid, ca, when), GSEC_ERR_MISMATCH);
}

/* --- keyCertSign -------------------------------------------------------- */

TEST(X509Policy, IntermediateWithoutKeyCertSignIsRefused) {
  auto ca = load("nokcs-ca.der");
  auto mid = load("nokcs-mid.der");
  auto leaf = load("nokcs-leaf.der");
  GSEC_X509 pm;
  ASSERT_EQ(gsec_x509_parse(mid.data(), mid.size(), &pm), GSEC_OK);
  EXPECT_EQ(pm.ca, 1);
  EXPECT_EQ(pm.key_usage_set, 1);
  EXPECT_EQ(pm.key_usage & 0x04u, 0u);
  EXPECT_EQ(path_mid(leaf, mid, ca, both_valid(leaf, ca)), GSEC_ERR_MISMATCH);
}

/* --- The signature algorithm must match the issuer's key ---------------- */

TEST(X509Policy, SignatureAlgorithmMustMatchIssuerKey) {
  auto rsa_leaf = load("rsa-leaf.der");
  auto p256_ca = load("p256-ca.der");
  GSEC_X509 pl;
  GSEC_X509 pc;
  ASSERT_EQ(gsec_x509_parse(rsa_leaf.data(), rsa_leaf.size(), &pl), GSEC_OK);
  ASSERT_EQ(gsec_x509_parse(p256_ca.data(), p256_ca.size(), &pc), GSEC_OK);
  EXPECT_EQ(pl.sig_key, GSEC_X509_RSA);
  EXPECT_EQ(pc.key, GSEC_X509_P256);
  /* An RSA signature offered to an EC key is refused before any verification
   * is attempted, rather than dispatched on the issuer's key type. */
  EXPECT_EQ(gsec_x509_signed_by(&pl, &pc), GSEC_ERR_MISMATCH);
}

int main(int argc, char ** argv) {
  ::testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
